### ISSUE TITLE
How to use this as a subchart?

### ISSUE THREAD

**Issue by sdrabblescripta** [Bluware-Inc/celery-flower-helm-chart#5]
Configured as a subchart:

```
- name: celery-flower
  repository: file://../celery-flower-helm-chart
  tags:
    - celery-flower
  version: ~0.0.0
```

in values.yaml:

```
celery:
  broker: "amqp://rabbitmq:rabbitmq@rabbitmq"
```

I get the error:

```
Error: INSTALLATION FAILED: execution error at (foo/charts/celery-flower/templates/deployment.yaml:33:26): required
```

Indicating `.Values.celery.broker` is not set.

How do I install this as a subchart?
